version: "2"
linters:
  enable:
    - durationcheck
    - forcetypeassert
  presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
issues:
  max-same-issues: 0
  exclude-rules:
    - linters:
        - forcetypeassert
      path: _test\.go
    - path: data
output:
  formats:
    - gofumpt